[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
tekenen = { path = "../tekenen",  features = ["image", "rust-embed"] }

[build-dependencies]
tekenen = { path = "../tekenen", features = ["preloader"] }

[profile.release]
debug = true