[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tekenen = { path = "../tekenen",  features = ["image"] }

rust-embed = "6.8.1"
image = "0.24.6"

[build-dependencies]
image = "0.24.6"

[profile.release]
debug = true