[package]
name = "example"
version = "0.1.0"
edition = "2021"

# WASM target
[target.'cfg(target_family = "wasm")'.dependencies]
tekenen = { path = "../tekenen", features = ["image", "wasm"] }

# NOT WASM target
[target.'cfg(not(target_family = "wasm"))'.dependencies]
tekenen = { path = "../tekenen", features = ["image", "native"] }
rouille = "3.6.2"

[dependencies]
wasm-bindgen = "0.2.73"

[build-dependencies]
tekenen = { path = "../tekenen", features = ["preloader", "native"] }

[profile.release]
debug = true

[lib]
crate-type = ["cdylib", "rlib"]