[package]
name = "tekenen"
version = "0.0.3"
edition = "2021"
description = "Simple library for drawing pixels in memory."
readme = "README.md"
license = "MIT"
repository = "https://github.com/Fritz179/tekenen"
documentation = "https://docs.rs/tekenen"

[dependencies]
sdl2 = { version ="0.35", optional = true }
image = { version = "0.24.6", optional = true }
rust-embed = { version = "6.8.1", optional = true }

[features]
default = ["sdl"]

sdl = ["sdl2"]
preloader = ["image"]

# TODO: add wasm support
# web = ["rocket"] 