[package]
name = "tekenen"
version = "0.0.2"
edition = "2021"
description = "Simple library for drawing pixels in memory."
license = "MIT"

[dependencies]
sdl2 = { version ="0.35", optional = true }
image = { version = "0.24.6", optional = true }
rust-embed = { version = "6.8.1", optional = true }

[features]
default = ["sdl"]

sdl = ["sdl2"]
preloader = ["image"]

# TODO: add wasm support
# web = ["rocket"] 