[package]
name = "tekenen"
version = "0.0.1"
edition = "2021"
description = "Simple library for drawing pixels in memory."
license = "MIT"

[dependencies]
sdl2 = { version ="0.35", optional = true }
image = { version = "0.24.6", optional = true }

[features]
default = ["sdl"]

sdl = ["sdl2"]

# TODO: add wasm support
# web = ["rocket"] 